// Fake Inventory Data - All brands and names are fictional

const INVENTORY_DATA = {
    clothes: {
        name: 'Clothes',
        icon: '👔',
        subcategories: {
            shirts: {
                name: 'Shirts',
                products: [
                    {
                        code: 'CLT-SHT-001',
                        name: 'Premium Cotton Dress Shirt',
                        manufacturer: 'Eleganto Apparel Co.',
                        category: 'clothes',
                        subcategory: 'shirts',
                        total: 150,
                        onHold: 12,
                        sold: 89,
                        requested: 8,
                        available: 41,
                        sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
                        colors: ['White', 'Light Blue', 'Navy', 'Black'],
                        wholesalePrice: 24.99,
                        retailPrice: 49.99,
                        msrp: 69.99,
                        material: '100% Egyptian Cotton',
                        weight: '180gsm',
                        features: ['Wrinkle-resistant', 'Breathable', 'Machine washable']
                    },
                    {
                        code: 'CLT-SHT-002',
                        name: 'Casual Linen Shirt',
                        manufacturer: 'Breezeway Fashion Inc.',
                        category: 'clothes',
                        subcategory: 'shirts',
                        total: 200,
                        onHold: 18,
                        sold: 142,
                        requested: 15,
                        available: 25,
                        sizes: ['S', 'M', 'L', 'XL'],
                        colors: ['Beige', 'Light Gray', 'Sky Blue', 'Olive'],
                        wholesalePrice: 18.50,
                        retailPrice: 39.99,
                        msrp: 54.99,
                        material: '100% Premium Linen',
                        weight: '150gsm',
                        features: ['Lightweight', 'UV protection', 'Quick-dry']
                    },
                    {
                        code: 'CLT-SHT-003',
                        name: 'Performance Sport Polo',
                        manufacturer: 'ActiveLife Brands',
                        category: 'clothes',
                        subcategory: 'shirts',
                        total: 180,
                        onHold: 20,
                        sold: 95,
                        requested: 22,
                        available: 43,
                        sizes: ['XS', 'S', 'M', 'L', 'XL'],
                        colors: ['Red', 'Navy', 'Forest Green', 'Charcoal'],
                        wholesalePrice: 16.75,
                        retailPrice: 34.99,
                        msrp: 49.99,
                        material: 'Polyester Blend',
                        weight: '160gsm',
                        features: ['Moisture-wicking', 'Anti-odor', 'Stretch fit']
                    },
                    {
                        code: 'CLT-SHT-004',
                        name: 'Classic Flannel Shirt',
                        manufacturer: 'Northwood Textiles',
                        category: 'clothes',
                        subcategory: 'shirts',
                        total: 120,
                        onHold: 8,
                        sold: 67,
                        requested: 5,
                        available: 40,
                        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
                        colors: ['Red Plaid', 'Blue Plaid', 'Gray Check', 'Green Tartan'],
                        wholesalePrice: 22.00,
                        retailPrice: 44.99,
                        msrp: 59.99,
                        material: 'Cotton Flannel',
                        weight: '220gsm',
                        features: ['Brushed finish', 'Warm', 'Durable']
                    }
                ]
            },
            pants: {
                name: 'Pants',
                products: [
                    {
                        code: 'CLT-PNT-001',
                        name: 'Slim Fit Chino Pants',
                        manufacturer: 'UrbanEdge Clothing',
                        category: 'clothes',
                        subcategory: 'pants',
                        total: 220,
                        onHold: 25,
                        sold: 156,
                        requested: 18,
                        available: 21,
                        sizes: ['28', '30', '32', '34', '36', '38', '40'],
                        colors: ['Khaki', 'Navy', 'Black', 'Olive'],
                        wholesalePrice: 28.50,
                        retailPrice: 59.99,
                        msrp: 79.99,
                        material: 'Cotton Twill',
                        weight: '280gsm',
                        features: ['Stretch fabric', 'Wrinkle-resistant', 'Multiple pockets']
                    },
                    {
                        code: 'CLT-PNT-002',
                        name: 'Premium Denim Jeans',
                        manufacturer: 'BlueLine Denim Works',
                        category: 'clothes',
                        subcategory: 'pants',
                        total: 300,
                        onHold: 35,
                        sold: 198,
                        requested: 42,
                        available: 25,
                        sizes: ['28', '30', '32', '34', '36', '38'],
                        colors: ['Dark Wash', 'Medium Wash', 'Light Wash', 'Black'],
                        wholesalePrice: 32.00,
                        retailPrice: 69.99,
                        msrp: 94.99,
                        material: 'Denim with Elastane',
                        weight: '340gsm',
                        features: ['Stretch comfort', 'Reinforced seams', 'Fade-resistant']
                    },
                    {
                        code: 'CLT-PNT-003',
                        name: 'Athletic Track Pants',
                        manufacturer: 'ActiveLife Brands',
                        category: 'clothes',
                        subcategory: 'pants',
                        total: 175,
                        onHold: 15,
                        sold: 124,
                        requested: 12,
                        available: 24,
                        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
                        colors: ['Black', 'Navy', 'Charcoal', 'Forest'],
                        wholesalePrice: 24.99,
                        retailPrice: 49.99,
                        msrp: 64.99,
                        material: 'Polyester Performance',
                        weight: '240gsm',
                        features: ['Moisture-wicking', 'Zippered pockets', 'Elastic waist']
                    }
                ]
            },
            dresses: {
                name: 'Dresses',
                products: [
                    {
                        code: 'CLT-DRS-001',
                        name: 'Summer Floral Sundress',
                        manufacturer: 'Blossom Fashion House',
                        category: 'clothes',
                        subcategory: 'dresses',
                        total: 140,
                        onHold: 16,
                        sold: 92,
                        requested: 14,
                        available: 18,
                        sizes: ['XS', 'S', 'M', 'L', 'XL'],
                        colors: ['Pink Floral', 'Blue Floral', 'Yellow Garden', 'Lavender'],
                        wholesalePrice: 35.00,
                        retailPrice: 74.99,
                        msrp: 99.99,
                        material: 'Cotton Voile',
                        weight: '120gsm',
                        features: ['Lightweight', 'Lined bodice', 'Side pockets']
                    },
                    {
                        code: 'CLT-DRS-002',
                        name: 'Elegant Evening Dress',
                        manufacturer: 'Glamour Couture Ltd.',
                        category: 'clothes',
                        subcategory: 'dresses',
                        total: 85,
                        onHold: 8,
                        sold: 54,
                        requested: 6,
                        available: 17,
                        sizes: ['XS', 'S', 'M', 'L'],
                        colors: ['Black', 'Navy', 'Burgundy', 'Emerald'],
                        wholesalePrice: 68.00,
                        retailPrice: 139.99,
                        msrp: 189.99,
                        material: 'Silk Blend',
                        weight: '180gsm',
                        features: ['Fully lined', 'Hidden zipper', 'Dry clean only']
                    },
                    {
                        code: 'CLT-DRS-003',
                        name: 'Casual Midi Dress',
                        manufacturer: 'EverydayChic Apparel',
                        category: 'clothes',
                        subcategory: 'dresses',
                        total: 160,
                        onHold: 12,
                        sold: 108,
                        requested: 10,
                        available: 30,
                        sizes: ['S', 'M', 'L', 'XL'],
                        colors: ['Navy', 'Charcoal', 'Olive', 'Rust'],
                        wholesalePrice: 28.50,
                        retailPrice: 59.99,
                        msrp: 79.99,
                        material: 'Jersey Knit',
                        weight: '200gsm',
                        features: ['Stretch fit', 'Machine washable', 'Wrinkle-free']
                    }
                ]
            },
            outerwear: {
                name: 'Outerwear',
                products: [
                    {
                        code: 'CLT-OUT-001',
                        name: 'Waterproof Rain Jacket',
                        manufacturer: 'StormShield Gear',
                        category: 'clothes',
                        subcategory: 'outerwear',
                        total: 95,
                        onHold: 10,
                        sold: 58,
                        requested: 8,
                        available: 19,
                        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
                        colors: ['Navy', 'Black', 'Forest Green', 'Gray'],
                        wholesalePrice: 48.00,
                        retailPrice: 99.99,
                        msrp: 134.99,
                        material: 'Waterproof Nylon',
                        weight: '320gsm',
                        features: ['Sealed seams', 'Adjustable hood', 'Reflective trim']
                    },
                    {
                        code: 'CLT-OUT-002',
                        name: 'Insulated Winter Parka',
                        manufacturer: 'Northwood Textiles',
                        category: 'clothes',
                        subcategory: 'outerwear',
                        total: 110,
                        onHold: 14,
                        sold: 72,
                        requested: 11,
                        available: 13,
                        sizes: ['S', 'M', 'L', 'XL'],
                        colors: ['Black', 'Navy', 'Olive', 'Charcoal'],
                        wholesalePrice: 85.00,
                        retailPrice: 179.99,
                        msrp: 249.99,
                        material: 'Down-filled Polyester',
                        weight: '580gsm',
                        features: ['Water-resistant', 'Fur-trim hood', 'Inner pockets']
                    },
                    {
                        code: 'CLT-OUT-003',
                        name: 'Lightweight Windbreaker',
                        manufacturer: 'ActiveLife Brands',
                        category: 'clothes',
                        subcategory: 'outerwear',
                        total: 130,
                        onHold: 11,
                        sold: 84,
                        requested: 9,
                        available: 26,
                        sizes: ['XS', 'S', 'M', 'L', 'XL'],
                        colors: ['Navy', 'Red', 'Teal', 'Yellow'],
                        wholesalePrice: 32.50,
                        retailPrice: 69.99,
                        msrp: 89.99,
                        material: 'Ripstop Nylon',
                        weight: '140gsm',
                        features: ['Packable', 'Wind-resistant', 'Mesh lining']
                    }
                ]
            }
        }
    },
    shoes: {
        name: 'Shoes',
        icon: '👟',
        subcategories: {
            sneakers: {
                name: 'Sneakers',
                products: [
                    {
                        code: 'SHO-SNK-001',
                        name: 'Urban Street Sneaker',
                        manufacturer: 'SoleStep Footwear',
                        category: 'shoes',
                        subcategory: 'sneakers',
                        total: 240,
                        onHold: 28,
                        sold: 165,
                        requested: 22,
                        available: 25,
                        sizes: ['6', '7', '8', '9', '10', '11', '12', '13'],
                        colors: ['White', 'Black', 'Gray', 'Navy'],
                        wholesalePrice: 38.00,
                        retailPrice: 79.99,
                        msrp: 109.99,
                        material: 'Synthetic Leather',
                        weight: '380g per shoe',
                        features: ['Cushioned sole', 'Breathable mesh', 'Non-slip']
                    },
                    {
                        code: 'SHO-SNK-002',
                        name: 'Performance Running Shoe',
                        manufacturer: 'VelocityRun Athletics',
                        category: 'shoes',
                        subcategory: 'sneakers',
                        total: 200,
                        onHold: 22,
                        sold: 148,
                        requested: 18,
                        available: 12,
                        sizes: ['6', '7', '8', '9', '10', '11', '12'],
                        colors: ['Blue/White', 'Black/Red', 'Gray/Lime', 'Navy/Orange'],
                        wholesalePrice: 52.00,
                        retailPrice: 109.99,
                        msrp: 149.99,
                        material: 'Engineered Mesh',
                        weight: '290g per shoe',
                        features: ['Responsive cushioning', 'Arch support', 'Reflective details']
                    },
                    {
                        code: 'SHO-SNK-003',
                        name: 'Classic Canvas Sneaker',
                        manufacturer: 'RetroKicks Co.',
                        category: 'shoes',
                        subcategory: 'sneakers',
                        total: 300,
                        onHold: 35,
                        sold: 212,
                        requested: 28,
                        available: 25,
                        sizes: ['5', '6', '7', '8', '9', '10', '11', '12'],
                        colors: ['White', 'Black', 'Red', 'Navy', 'Beige'],
                        wholesalePrice: 22.50,
                        retailPrice: 44.99,
                        msrp: 59.99,
                        material: 'Canvas Upper',
                        weight: '320g per shoe',
                        features: ['Vulcanized sole', 'Classic design', 'Machine washable']
                    }
                ]
            },
            boots: {
                name: 'Boots',
                products: [
                    {
                        code: 'SHO-BOT-001',
                        name: 'Rugged Work Boot',
                        manufacturer: 'IronForge Footwear',
                        category: 'shoes',
                        subcategory: 'boots',
                        total: 150,
                        onHold: 18,
                        sold: 96,
                        requested: 15,
                        available: 21,
                        sizes: ['7', '8', '9', '10', '11', '12', '13'],
                        colors: ['Brown', 'Black', 'Tan'],
                        wholesalePrice: 68.00,
                        retailPrice: 139.99,
                        msrp: 189.99,
                        material: 'Full-grain Leather',
                        weight: '680g per boot',
                        features: ['Steel toe cap', 'Slip-resistant', 'Oil-resistant sole']
                    },
                    {
                        code: 'SHO-BOT-002',
                        name: 'Winter Insulated Boot',
                        manufacturer: 'ArcticTrail Outdoor',
                        category: 'shoes',
                        subcategory: 'boots',
                        total: 120,
                        onHold: 14,
                        sold: 78,
                        requested: 12,
                        available: 16,
                        sizes: ['6', '7', '8', '9', '10', '11', '12'],
                        colors: ['Black', 'Brown', 'Gray'],
                        wholesalePrice: 75.00,
                        retailPrice: 154.99,
                        msrp: 209.99,
                        material: 'Waterproof Leather',
                        weight: '720g per boot',
                        features: ['Thinsulate lining', 'Waterproof', 'Snow traction']
                    },
                    {
                        code: 'SHO-BOT-003',
                        name: 'Chelsea Ankle Boot',
                        manufacturer: 'Eleganto Footwear',
                        category: 'shoes',
                        subcategory: 'boots',
                        total: 100,
                        onHold: 12,
                        sold: 64,
                        requested: 9,
                        available: 15,
                        sizes: ['6', '7', '8', '9', '10', '11'],
                        colors: ['Black', 'Brown', 'Tan'],
                        wholesalePrice: 58.00,
                        retailPrice: 119.99,
                        msrp: 159.99,
                        material: 'Suede Leather',
                        weight: '450g per boot',
                        features: ['Elastic side panels', 'Pull-on style', 'Cushioned insole']
                    }
                ]
            },
            sandals: {
                name: 'Sandals',
                products: [
                    {
                        code: 'SHO-SND-001',
                        name: 'Comfort Slide Sandal',
                        manufacturer: 'BeachBreeze Footwear',
                        category: 'shoes',
                        subcategory: 'sandals',
                        total: 220,
                        onHold: 24,
                        sold: 158,
                        requested: 20,
                        available: 18,
                        sizes: ['6', '7', '8', '9', '10', '11', '12'],
                        colors: ['Black', 'Navy', 'Gray', 'Tan'],
                        wholesalePrice: 18.50,
                        retailPrice: 39.99,
                        msrp: 54.99,
                        material: 'EVA Foam',
                        weight: '180g per sandal',
                        features: ['Contoured footbed', 'Lightweight', 'Water-friendly']
                    },
                    {
                        code: 'SHO-SND-002',
                        name: 'Sport Adventure Sandal',
                        manufacturer: 'TrailBlazer Gear',
                        category: 'shoes',
                        subcategory: 'sandals',
                        total: 180,
                        onHold: 20,
                        sold: 126,
                        requested: 16,
                        available: 18,
                        sizes: ['7', '8', '9', '10', '11', '12'],
                        colors: ['Black/Gray', 'Navy/Teal', 'Brown/Tan'],
                        wholesalePrice: 32.00,
                        retailPrice: 69.99,
                        msrp: 94.99,
                        material: 'Nylon Webbing',
                        weight: '320g per sandal',
                        features: ['Adjustable straps', 'Toe protection', 'Hiking sole']
                    }
                ]
            },
            formal: {
                name: 'Formal Shoes',
                products: [
                    {
                        code: 'SHO-FRM-001',
                        name: 'Oxford Dress Shoe',
                        manufacturer: 'Eleganto Footwear',
                        category: 'shoes',
                        subcategory: 'formal',
                        total: 130,
                        onHold: 15,
                        sold: 88,
                        requested: 12,
                        available: 15,
                        sizes: ['7', '8', '9', '10', '11', '12'],
                        colors: ['Black', 'Brown', 'Burgundy'],
                        wholesalePrice: 62.00,
                        retailPrice: 129.99,
                        msrp: 179.99,
                        material: 'Genuine Leather',
                        weight: '520g per shoe',
                        features: ['Leather sole', 'Goodyear welt', 'Hand-stitched']
                    },
                    {
                        code: 'SHO-FRM-002',
                        name: 'Classic Loafer',
                        manufacturer: 'Prestige Shoes Ltd.',
                        category: 'shoes',
                        subcategory: 'formal',
                        total: 110,
                        onHold: 13,
                        sold: 72,
                        requested: 10,
                        available: 15,
                        sizes: ['7', '8', '9', '10', '11', '12'],
                        colors: ['Black', 'Brown', 'Navy'],
                        wholesalePrice: 54.00,
                        retailPrice: 114.99,
                        msrp: 154.99,
                        material: 'Patent Leather',
                        weight: '480g per shoe',
                        features: ['Slip-on design', 'Penny strap', 'Cushioned insole']
                    }
                ]
            }
        }
    },
    accessories: {
        name: 'Accessories',
        icon: '👜',
        subcategories: {
            bags: {
                name: 'Bags',
                products: [
                    {
                        code: 'ACC-BAG-001',
                        name: 'Professional Laptop Backpack',
                        manufacturer: 'CarryAll Solutions',
                        category: 'accessories',
                        subcategory: 'bags',
                        total: 160,
                        onHold: 18,
                        sold: 112,
                        requested: 14,
                        available: 16,
                        sizes: ['One Size'],
                        colors: ['Black', 'Navy', 'Gray', 'Charcoal'],
                        wholesalePrice: 42.00,
                        retailPrice: 89.99,
                        msrp: 124.99,
                        material: 'Water-resistant Polyester',
                        weight: '850g',
                        features: ['Laptop compartment', 'USB charging port', 'Multiple pockets']
                    },
                    {
                        code: 'ACC-BAG-002',
                        name: 'Canvas Tote Bag',
                        manufacturer: 'EcoCarry Bags',
                        category: 'accessories',
                        subcategory: 'bags',
                        total: 250,
                        onHold: 30,
                        sold: 182,
                        requested: 24,
                        available: 14,
                        sizes: ['One Size'],
                        colors: ['Natural', 'Black', 'Navy', 'Olive'],
                        wholesalePrice: 12.50,
                        retailPrice: 29.99,
                        msrp: 39.99,
                        material: 'Organic Cotton Canvas',
                        weight: '320g',
                        features: ['Eco-friendly', 'Reinforced handles', 'Machine washable']
                    },
                    {
                        code: 'ACC-BAG-003',
                        name: 'Leather Messenger Bag',
                        manufacturer: 'Heritage Leather Goods',
                        category: 'accessories',
                        subcategory: 'bags',
                        total: 90,
                        onHold: 10,
                        sold: 58,
                        requested: 8,
                        available: 14,
                        sizes: ['One Size'],
                        colors: ['Brown', 'Black', 'Tan'],
                        wholesalePrice: 78.00,
                        retailPrice: 159.99,
                        msrp: 219.99,
                        material: 'Full-grain Leather',
                        weight: '1200g',
                        features: ['Adjustable strap', 'Interior organizer', 'Brass hardware']
                    }
                ]
            },
            belts: {
                name: 'Belts',
                products: [
                    {
                        code: 'ACC-BLT-001',
                        name: 'Classic Leather Belt',
                        manufacturer: 'Eleganto Accessories',
                        category: 'accessories',
                        subcategory: 'belts',
                        total: 200,
                        onHold: 22,
                        sold: 145,
                        requested: 18,
                        available: 15,
                        sizes: ['32', '34', '36', '38', '40', '42', '44'],
                        colors: ['Black', 'Brown', 'Tan'],
                        wholesalePrice: 18.00,
                        retailPrice: 39.99,
                        msrp: 54.99,
                        material: 'Genuine Leather',
                        weight: '180g',
                        features: ['Reversible', 'Metal buckle', 'Adjustable']
                    },
                    {
                        code: 'ACC-BLT-002',
                        name: 'Tactical Nylon Belt',
                        manufacturer: 'ToughGear Co.',
                        category: 'accessories',
                        subcategory: 'belts',
                        total: 180,
                        onHold: 20,
                        sold: 128,
                        requested: 16,
                        available: 16,
                        sizes: ['S', 'M', 'L', 'XL'],
                        colors: ['Black', 'Coyote', 'Olive', 'Gray'],
                        wholesalePrice: 14.50,
                        retailPrice: 32.99,
                        msrp: 44.99,
                        material: 'Ballistic Nylon',
                        weight: '140g',
                        features: ['Quick-release buckle', 'Heavy-duty', 'Adjustable']
                    }
                ]
            },
            hats: {
                name: 'Hats',
                products: [
                    {
                        code: 'ACC-HAT-001',
                        name: 'Classic Baseball Cap',
                        manufacturer: 'CapStyle Inc.',
                        category: 'accessories',
                        subcategory: 'hats',
                        total: 280,
                        onHold: 32,
                        sold: 198,
                        requested: 26,
                        available: 24,
                        sizes: ['One Size Adjustable'],
                        colors: ['Black', 'Navy', 'Gray', 'Red', 'White'],
                        wholesalePrice: 8.50,
                        retailPrice: 19.99,
                        msrp: 27.99,
                        material: 'Cotton Twill',
                        weight: '85g',
                        features: ['Adjustable strap', 'Curved brim', 'Breathable']
                    },
                    {
                        code: 'ACC-HAT-002',
                        name: 'Winter Knit Beanie',
                        manufacturer: 'CozyHead Knits',
                        category: 'accessories',
                        subcategory: 'hats',
                        total: 220,
                        onHold: 25,
                        sold: 162,
                        requested: 20,
                        available: 13,
                        sizes: ['One Size'],
                        colors: ['Black', 'Navy', 'Gray', 'Burgundy', 'Forest'],
                        wholesalePrice: 10.00,
                        retailPrice: 24.99,
                        msrp: 34.99,
                        material: 'Acrylic Knit',
                        weight: '95g',
                        features: ['Fleece-lined', 'Stretchy', 'Warm']
                    },
                    {
                        code: 'ACC-HAT-003',
                        name: 'Wide Brim Sun Hat',
                        manufacturer: 'SunShield Headwear',
                        category: 'accessories',
                        subcategory: 'hats',
                        total: 150,
                        onHold: 16,
                        sold: 104,
                        requested: 12,
                        available: 18,
                        sizes: ['S/M', 'L/XL'],
                        colors: ['Khaki', 'Navy', 'Olive', 'Black'],
                        wholesalePrice: 15.00,
                        retailPrice: 34.99,
                        msrp: 47.99,
                        material: 'UPF 50+ Fabric',
                        weight: '120g',
                        features: ['UV protection', 'Breathable mesh', 'Adjustable chin strap']
                    }
                ]
            },
            jewelry: {
                name: 'Jewelry',
                products: [
                    {
                        code: 'ACC-JWL-001',
                        name: 'Minimalist Watch',
                        manufacturer: 'TimeCraft Timepieces',
                        category: 'accessories',
                        subcategory: 'jewelry',
                        total: 120,
                        onHold: 14,
                        sold: 82,
                        requested: 11,
                        available: 13,
                        sizes: ['One Size'],
                        colors: ['Silver/White', 'Gold/Black', 'Rose Gold/Navy'],
                        wholesalePrice: 45.00,
                        retailPrice: 99.99,
                        msrp: 139.99,
                        material: 'Stainless Steel',
                        weight: '65g',
                        features: ['Quartz movement', 'Water-resistant', 'Interchangeable strap']
                    },
                    {
                        code: 'ACC-JWL-002',
                        name: 'Braided Leather Bracelet',
                        manufacturer: 'ArtisanWear Crafts',
                        category: 'accessories',
                        subcategory: 'jewelry',
                        total: 200,
                        onHold: 22,
                        sold: 148,
                        requested: 18,
                        available: 12,
                        sizes: ['S', 'M', 'L'],
                        colors: ['Brown', 'Black', 'Tan', 'Navy'],
                        wholesalePrice: 12.00,
                        retailPrice: 29.99,
                        msrp: 39.99,
                        material: 'Genuine Leather',
                        weight: '15g',
                        features: ['Handcrafted', 'Magnetic clasp', 'Adjustable']
                    },
                    {
                        code: 'ACC-JWL-003',
                        name: 'Sterling Silver Cufflinks',
                        manufacturer: 'Eleganto Accessories',
                        category: 'accessories',
                        subcategory: 'jewelry',
                        total: 80,
                        onHold: 9,
                        sold: 52,
                        requested: 7,
                        available: 12,
                        sizes: ['One Size'],
                        colors: ['Silver', 'Silver/Black', 'Silver/Blue'],
                        wholesalePrice: 32.00,
                        retailPrice: 69.99,
                        msrp: 94.99,
                        material: 'Sterling Silver',
                        weight: '18g per pair',
                        features: ['Gift boxed', 'Polished finish', 'Swivel bar']
                    }
                ]
            }
        }
    }
};
